# Generated by Django 6.1.1 on 2026-09-30 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de alimento',
                'verbose_name_plural': 'Categorías de alimentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Once', 'Once'), ('Cena', 'Cena'), ('Snack', 'Snack')], default='Almuerzo', max_length=20)),
                ('descripcion', models.TextField(help_text='Ej: Dos panes con queso, un café y una manzana.')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('gasto_asociado', models.BooleanField(default=False, help_text='¿Generó un gasto en Pluto?')),
            ],
            options={
                'verbose_name': 'Registro de comida',
                'verbose_name_plural': 'Registros de comidas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('unidad', models.CharField(choices=[('KG', 'Kilogramos'), ('GR', 'Gramos'), ('L', 'Litros'), ('ML', 'Mililitros'), ('UN', 'Unidades')], default='UN', max_length=2)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Punto de reabastecimiento para alertas.', max_digits=8)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='demeter.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemDespensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='demeter.producto')),
            ],
            options={
                'verbose_name': 'Ítem en despensa',
                'verbose_name_plural': 'Ítems en despensa',
                'ordering': ['fecha_vencimiento', 'producto__nombre'],
            },
        ),
    ]
