# Generated by Django 6.1.1 on 2026-09-30 23:50

import galaxia.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_usuario', models.TextField()),
                ('resultado_json', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('expirada', 'Expirada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(default=galaxia.models.propuesta_expira_en)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Propuesta de IA',
                'verbose_name_plural': 'Propuestas de IA',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'expira_en'], name='galaxia_pro_estado_97ed18_idx')],
            },
        ),
    ]
