# Generated by Django 6.1.1 on 2026-09-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('Personal', 'Personal'), ('Académica', 'Académica'), ('Trabajo', 'Trabajo')], max_length=10)),
                ('refresh_token', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta de Google',
                'verbose_name_plural': 'Cuentas de Google',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('modulo_origen', models.CharField(default='Cronos', max_length=50)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cronos.cuentagoogle')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
